# Generated by Django 4.2.11 on 2024-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='recipe_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
