# Generated by Django 4.2.11 on 2024-10-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_fooditem_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='recipe_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
